In [ ]:
from google.colab import files
uploaded = files.upload()


Saving Lab Session Data.xlsx to Lab Session Data.xlsx


In [ ]:
import pandas as pd
import numpy as np

data = pd.read_excel("Lab Session Data.xlsx", sheet_name="Purchase data")

X = data[["Candies (#)", "Mangoes (Kg)", "Milk Packets (#)"]].values
Y = data["Payment (Rs)"].values

rank_X = np.linalg.matrix_rank(X)
X_pinv = np.linalg.pinv(X)
price_c = X_pinv @ Y

print("Rank of X:", rank_X)
print("Prices:", price_c)


Rank of X: 3
Prices: [ 1. 55. 18.]


In [ ]:
import pandas as pd
import numpy as np

data = pd.read_excel("Lab Session Data.xlsx", sheet_name="Purchase data")
X = data[["Candies (#)", "Mangoes (Kg)", "Milk Packets (#)"]].values
Y = data["Payment (Rs)"].values

customer_class = []

for payment in Y:
    if payment > 200:
        customer_class.append("RICH")
    else:
        customer_class.append("POOR")

data["Customer Class"] = customer_class

print("Feature matrix X:\n", X)
print("\nPayment vector Y:\n", Y)
print("\nCustomer Classification (RICH / POOR):\n")
print(data[["Customer", "Payment (Rs)", "Customer Class"]])


Feature matrix X:
 [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

Payment vector Y:
 [386 289 393 110 280 167 271 274 148 198]

Customer Classification (RICH / POOR):

  Customer  Payment (Rs) Customer Class
0      C_1           386           RICH
1      C_2           289           RICH
2      C_3           393           RICH
3      C_4           110           POOR
4      C_5           280           RICH
5      C_6           167           POOR
6      C_7           271           RICH
7      C_8           274           RICH
8      C_9           148           POOR
9     C_10           198           POOR
